services:
  db:
    image: postgres:16-alpine
    container_name: taarifa_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taarifa_network

  backend:
    build:
      context: ./taarifa_backend
      dockerfile: Dockerfile
    container_name: taarifa_backend
    restart: unless-stopped
    
    
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taarifa_network

  frontend:
    build:
      context: ./taarifa_frontend
      dockerfile: Dockerfile
      args:
        - VITE_GRAPHQL_URL=http://localhost:8001/graphql/
        - VITE_API_URL=http://localhost:8001/api/
    container_name: taarifa_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - taarifa_network

volumes:
  postgres_data:

networks:
  taarifa_network:
    driver: bridge